language: python
python:
  - "3.6"
install:
  pip install -r requirements.txt
script:
  - python get_info.py
after_success:
  - git add --all -v
  - git commit -m "`TZ=Asia/Shanghai date`" -v
  - git push https://$TOKEN@github.com/mark0smith/Hexo_theme_stats.git master -v
