language: python
python:
  - "3.6"
install:
  pip install -r requirements.txt
deploy:
  - skip_cleanup: true
script:
  - python get_info.py
after_success:
  - git remote rm origin
  - git remote add origin https://mark0smith:$TOKEN@github.com/mark0smith/Hexo_theme_stats.git
  - git add --all -v
  - git config --global user.email "you@example.com"
  - git config --global user.name "mark0smith"
  - git commit -m "`TZ=Asia/Shanghai date`" -v
  - git push origin master -v
